"""SQLAlchemy ORM models for PointlesSQL's own metadata database.

The ORM is split into per-domain sub-modules, all re-exported here so
that ``from pointlessql.models import Base`` (used by the Alembic
env.py) and every ``from pointlessql.models import <Model>`` call site
keep resolving unchanged.

SQLAlchemy resolves ``ForeignKey("table.col")`` strings lazily at
mapper-configuration time — once this module has imported every
sub-module — so import order does not affect FK resolution.  The
per-domain grouping below documents the cross-module FK relationships:

* ``base`` (Base class)
* ``auth`` (User — referenced by Job, Dashboard, SavedQuery, Alert)
* ``audit`` package (AuditLog, AuditSink, GovernanceEvent,
  SavedAuditQuery, AnomalyAck, BranchAuditLog — no model FKs)
* ``scheduler`` (Job, JobRun, JobTask, TaskRun, JobLog — Job FKs User)
* ``catalog`` package (Dashboard FKs Job/User; QueryHistory +
  RateLimitEvent + SavedQuery + TableStats + QueryHistoryTable +
  RecentTable + AutoloadCheckpoint + DataProduct +
  DataProductContractEvent + SyncRun)
* ``alerts`` (Alert FKs SavedQuery + User + Job; AlertDestination
  + AlertEvent FK Alert)
* ``notebook`` (NotebookOutput, NotebookCellRun, NotebookCellRunSource
  — no model FKs; the ``agent_run_id`` column is logical-link only)
* ``lens`` package (LensSession, LensMessage, LensPinnedAnswer,
  LensProviderCreds — read-only Q&A surface; FKs to
  Workspace + User)
* ``agent`` package (AgentRun, AgentRunSource, AgentRunOperation,
  AgentRunEvent, AgentRunToolCall, AgentReview, ReviewDestination,
  RewriteAttempt — internal FKs to AgentRun)
* ``workspace`` package (Workspace, WorkspaceMember,
  WorkspaceCatalogPin, WorkspaceRepo, WorkspaceRepoSecret, ApiKey —
  governance container; ``users.default_workspace_id`` and
  ``api_keys.workspace_id`` FKs land in the same migration)
"""

from __future__ import annotations

from pointlessql.models.access_requests import AccessRequest
from pointlessql.models.actionable_signals import ActionableSignal
from pointlessql.models.agent import (
    AVATAR_KINDS,
    REVIEW_SEVERITIES,
    REWRITE_VERDICTS,
    VERDICT_AUTO_REWRITE_FAILED,
    VERDICT_AUTO_REWRITE_SUCCEEDED,
    VERDICT_HUMAN_APPROVAL_REQUIRED,
    VERDICT_ORIGINAL_APPROVED,
    Agent,
    AgentReview,
    AgentRun,
    AgentRunEvent,
    AgentRunOperation,
    AgentRunSource,
    AgentRunToolCall,
    ReviewDestination,
    RewriteAttempt,
)
from pointlessql.models.alerts import Alert, AlertDestination, AlertEvent
from pointlessql.models.audit import (
    BRANCH_ACTIONS,
    SINK_TYPES,
    AnomalyAck,
    AuditLog,
    AuditSavedFilter,
    AuditSink,
    BranchAuditLog,
    GovernanceEvent,
    SavedAuditQuery,
)
from pointlessql.models.auth import User
from pointlessql.models.autoloader import AutoloaderFile
from pointlessql.models.base import Base
from pointlessql.models.bi_dashboards import (
    BI_WIDGET_KINDS,
    BiDashboard,
    BiDashboardWidget,
)
from pointlessql.models.bi_schedules import (
    BiDashboardSchedule,
    BiDashboardSnapshot,
)
from pointlessql.models.catalog import (
    ASSERTION_KINDS,
    BITEMPORAL_ENFORCEMENT_MODES,
    BREAKING_CHANGE_POLICIES,
    CANDIDATE_DECISIONS,
    CHANGE_KINDS,
    CLASSIFICATIONS,
    CONTRACT_EVENT_OUTCOMES,
    CONTRACT_TEST_SEVERITIES,
    CONTRACT_TEST_STATUSES,
    DOMAIN_ARCHETYPES,
    DOMAIN_MEMBER_ROLES,
    DP_TRANSFORMATION_KINDS,
    ENCRYPTION_CLASSES,
    ENTITY_LINK_KINDS,
    FORGET_STATUSES,
    GLOSSARY_TERM_RELATION_KINDS,
    INFRASTRUCTURE_STORAGE_CLASSES,
    INPUT_PORT_KINDS,
    LIFECYCLE_STATES,
    MASKING_STRATEGIES,
    MEASURABLE_SLO_KINDS,
    OUTPUT_PORT_KINDS,
    POLICY_MODULE_EFFECTS,
    QUERY_KINDS,
    QUOTA_ENFORCEMENT_MODES,
    SLO_COMPARATORS,
    SLO_KINDS,
    AutoloadCheckpoint,
    Dashboard,
    DataProduct,
    DataProductAvailabilityProbe,
    DataProductBitemporalPolicy,
    DataProductCanvasGraph,
    DataProductColumnClassification,
    DataProductComment,
    DataProductContractEvent,
    DataProductContractTest,
    DataProductContractTestResult,
    DataProductCostBucketHourly,
    DataProductEndorsement,
    DataProductEntity,
    DataProductEventDelivery,
    DataProductEventSubscription,
    DataProductFixture,
    DataProductForgetRequest,
    DataProductInfrastructure,
    DataProductInputPort,
    DataProductOutputPort,
    DataProductPolicy,
    DataProductQueryCost,
    DataProductQueryPerfSample,
    DataProductRating,
    DataProductReview,
    DataProductSemanticConcept,
    DataProductSLO,
    DataProductStatistics,
    DataProductTransformation,
    DataProductTrending,
    DataProductUseCase,
    DataProductUseCaseVote,
    Domain,
    DomainMember,
    EntityLink,
    EntityLinkCandidate,
    GlossaryTerm,
    GlossaryTermColumn,
    GlossaryTermRelation,
    MeshEntity,
    MeshEntityBinding,
    OutputPortSchemaVersion,
    PolicyModule,
    PolicyModuleDecision,
    QueryHistory,
    QueryHistoryTable,
    RateLimitEvent,
    RecentTable,
    SavedQuery,
    SyncRun,
    TableStats,
    WorkspaceGovernancePolicy,
)
from pointlessql.models.dp_releases import DataProductRelease
from pointlessql.models.editor_chat import (
    CHAT_PROPOSAL_KINDS,
    CHAT_PROPOSAL_STATUSES,
    NOTEBOOK_CELL_PROPOSAL_ACTIONS,
    NOTEBOOK_CELL_PROPOSAL_STATUSES,
    ChatProposal,
    EditorChatSession,
    NotebookCellProposal,
)
from pointlessql.models.genie import (
    GENIE_FEEDBACK_VALUES,
    GENIE_MESSAGE_ROLES,
    GENIE_MESSAGE_STATUSES,
    GenieMessage,
    GenieSpace,
    GenieTrustedAsset,
)
from pointlessql.models.hosted_apps import (
    HOSTED_APP_KINDS,
    HOSTED_APP_STATES,
    HostedApp,
)
from pointlessql.models.ingest import (
    INGEST_PULL_MODES,
    INGEST_SOURCE_KINDS,
    IngestSource,
)
from pointlessql.models.lens import (
    LENS_PROVIDERS,
    LensMessage,
    LensPinnedAnswer,
    LensProviderCreds,
    LensSession,
)
from pointlessql.models.lineage import (
    REJECT_REASONS,
    TRANSFORM_KINDS,
    CdfTailEvent,
    CdfTailSubscription,
    ExpectedLineageInbound,
    LineageColumnMap,
    LineageRowEdge,
    LineageRowReject,
    LineageValueChange,
    UnattributedWrite,
)
from pointlessql.models.mcp_registry import (
    MCP_SERVICE_TRANSPORTS,
    McpService,
    McpServiceTool,
)
from pointlessql.models.notebook import (
    NOTEBOOK_CELL_SEQUENCE_PROPOSAL_STATUSES,
    CoeditBusMessage,
    Notebook,
    NotebookBranchBinding,
    NotebookCellAuthorship,
    NotebookCellProvenance,
    NotebookCellRun,
    NotebookCellRunSource,
    NotebookCellSequenceProposal,
    NotebookCrdtState,
    NotebookJobLink,
    NotebookOutput,
    NotebookPermission,
    NotebookReplay,
    NotebookRevision,
    NotebookRevisionFact,
    NotebookShare,
    NotebookTag,
    NotebookWidget,
)
from pointlessql.models.notifications import (
    FeedReadMarker,
    UserNotification,
    UserWebhookSubscription,
)
from pointlessql.models.pipelines import (
    PIPELINE_DATASET_KINDS,
    PIPELINE_EXPECTATION_ACTIONS,
    PIPELINE_RUN_STATES,
    Pipeline,
    PipelineCursor,
    PipelineRun,
)
from pointlessql.models.quality_monitoring import (
    QUALITY_ANOMALY_KINDS,
    QUALITY_ANOMALY_SEVERITIES,
    QualityAnomaly,
    QualityMonitor,
    TableProfileSnapshot,
)
from pointlessql.models.saved_views import (
    SAVED_VIEW_PARAM_TYPES,
    SavedView,
)
from pointlessql.models.scheduler import (
    Job,
    JobLog,
    JobRun,
    JobTask,
    TaskRun,
)
from pointlessql.models.secret_scopes import (
    SECRET_SCOPE_PERMISSIONS,
    SecretScope,
    SecretScopeAcl,
    SecretScopeSecret,
)
from pointlessql.models.serving import (
    SERVING_ENDPOINT_STATES,
    ServingEndpoint,
)
from pointlessql.models.sharing_providers import SharingProvider
from pointlessql.models.social import (
    BADGE_KEYS,
    DataProductTopic,
    Topic,
    UserBadge,
    UserFollow,
    UserProfile,
    UserTopicFollow,
)
from pointlessql.models.synced_table_snapshots import (
    SNAPSHOT_STATUSES,
    SyncedTableSnapshot,
)
from pointlessql.models.synced_tables import (
    SYNCED_TABLE_MODES,
    SYNCED_TABLE_STATUSES,
    SyncedTable,
)
from pointlessql.models.system_keys import SystemKey
from pointlessql.models.tag_policies import TagPolicyRule
from pointlessql.models.vector import VectorIndex
from pointlessql.models.workspace import (
    SQL_STATEMENT_STATES,
    WORKSPACE_PIN_MODES,
    WORKSPACE_REPO_PROVIDER_KINDS,
    WORKSPACE_REPO_SECRET_KINDS,
    WORKSPACE_REPO_SYNC_STATES,
    WORKSPACE_ROLES,
    ApiKey,
    ApiKeyCatalogGrant,
    ApiKeyIpGrant,
    ApiKeyUsageBucket,
    SqlStatement,
    Workspace,
    WorkspaceCatalogPin,
    WorkspaceMember,
    WorkspaceRepo,
    WorkspaceRepoSecret,
)

__all__ = [
    "AccessRequest",
    "ActionableSignal",
    "AgentReview",
    "AgentRun",
    "AgentRunEvent",
    "AgentRunOperation",
    "AgentRunSource",
    "AgentRunToolCall",
    "Alert",
    "AlertDestination",
    "AlertEvent",
    "AVATAR_KINDS",
    "Agent",
    "AnomalyAck",
    "ApiKey",
    "ApiKeyCatalogGrant",
    "ApiKeyIpGrant",
    "ApiKeyUsageBucket",
    "BADGE_KEYS",
    "CHAT_PROPOSAL_KINDS",
    "CHAT_PROPOSAL_STATUSES",
    "ChatProposal",
    "AuditLog",
    "AuditSavedFilter",
    "AuditSink",
    "AutoloadCheckpoint",
    "BRANCH_ACTIONS",
    "BI_WIDGET_KINDS",
    "Base",
    "BiDashboard",
    "BiDashboardSchedule",
    "BiDashboardSnapshot",
    "BiDashboardWidget",
    "BranchAuditLog",
    "CLASSIFICATIONS",
    "CONTRACT_EVENT_OUTCOMES",
    "DOMAIN_ARCHETYPES",
    "DOMAIN_MEMBER_ROLES",
    "DP_TRANSFORMATION_KINDS",
    "ENCRYPTION_CLASSES",
    "ENTITY_LINK_KINDS",
    "QUERY_KINDS",
    "QUOTA_ENFORCEMENT_MODES",
    "FORGET_STATUSES",
    "BITEMPORAL_ENFORCEMENT_MODES",
    "GLOSSARY_TERM_RELATION_KINDS",
    "ASSERTION_KINDS",
    "BREAKING_CHANGE_POLICIES",
    "CANDIDATE_DECISIONS",
    "CHANGE_KINDS",
    "CONTRACT_TEST_SEVERITIES",
    "CONTRACT_TEST_STATUSES",
    "INFRASTRUCTURE_STORAGE_CLASSES",
    "INPUT_PORT_KINDS",
    "LIFECYCLE_STATES",
    "MASKING_STRATEGIES",
    "MEASURABLE_SLO_KINDS",
    "OUTPUT_PORT_KINDS",
    "POLICY_MODULE_EFFECTS",
    "SLO_COMPARATORS",
    "SLO_KINDS",
    "CdfTailEvent",
    "CdfTailSubscription",
    "DataProduct",
    "DataProductAvailabilityProbe",
    "DataProductBitemporalPolicy",
    "DataProductCanvasGraph",
    "DataProductColumnClassification",
    "DataProductEventDelivery",
    "DataProductEventSubscription",
    "DataProductInfrastructure",
    "DataProductRating",
    "DataProductUseCase",
    "DataProductUseCaseVote",
    "DataProductComment",
    "DataProductContractEvent",
    "DataProductContractTest",
    "DataProductContractTestResult",
    "DataProductCostBucketHourly",
    "DataProductFixture",
    "DataProductEndorsement",
    "DataProductEntity",
    "DataProductForgetRequest",
    "DataProductInputPort",
    "DataProductOutputPort",
    "DataProductPolicy",
    "DataProductQueryCost",
    "DataProductQueryPerfSample",
    "DataProductRelease",
    "DataProductReview",
    "DataProductSemanticConcept",
    "DataProductSLO",
    "DataProductStatistics",
    "DataProductTransformation",
    "DataProductTrending",
    "Dashboard",
    "Domain",
    "DomainMember",
    "EntityLink",
    "EntityLinkCandidate",
    "GlossaryTerm",
    "GlossaryTermColumn",
    "GlossaryTermRelation",
    "MCP_SERVICE_TRANSPORTS",
    "McpService",
    "McpServiceTool",
    "MeshEntity",
    "MeshEntityBinding",
    "OutputPortSchemaVersion",
    "PIPELINE_DATASET_KINDS",
    "PIPELINE_EXPECTATION_ACTIONS",
    "PIPELINE_RUN_STATES",
    "Pipeline",
    "PipelineCursor",
    "PipelineRun",
    "PolicyModule",
    "PolicyModuleDecision",
    "WorkspaceGovernancePolicy",
    "EditorChatSession",
    "ExpectedLineageInbound",
    "GovernanceEvent",
    "HOSTED_APP_KINDS",
    "HOSTED_APP_STATES",
    "HostedApp",
    "INGEST_PULL_MODES",
    "INGEST_SOURCE_KINDS",
    "IngestSource",
    "Job",
    "JobLog",
    "JobRun",
    "JobTask",
    "LENS_PROVIDERS",
    "LensMessage",
    "LensPinnedAnswer",
    "LensProviderCreds",
    "LensSession",
    "LineageColumnMap",
    "LineageRowEdge",
    "LineageRowReject",
    "LineageValueChange",
    "REJECT_REASONS",
    "TRANSFORM_KINDS",
    "NOTEBOOK_CELL_PROPOSAL_ACTIONS",
    "NOTEBOOK_CELL_PROPOSAL_STATUSES",
    "NOTEBOOK_CELL_SEQUENCE_PROPOSAL_STATUSES",
    "CoeditBusMessage",
    "Notebook",
    "NotebookBranchBinding",
    "NotebookCellAuthorship",
    "NotebookCellProposal",
    "NotebookCellProvenance",
    "NotebookCellSequenceProposal",
    "NotebookCellRun",
    "NotebookCellRunSource",
    "NotebookCrdtState",
    "NotebookJobLink",
    "NotebookOutput",
    "NotebookPermission",
    "NotebookReplay",
    "NotebookRevision",
    "NotebookRevisionFact",
    "NotebookShare",
    "NotebookTag",
    "NotebookWidget",
    "QUALITY_ANOMALY_KINDS",
    "QUALITY_ANOMALY_SEVERITIES",
    "QualityAnomaly",
    "QualityMonitor",
    "QueryHistory",
    "QueryHistoryTable",
    "REVIEW_SEVERITIES",
    "RateLimitEvent",
    "RecentTable",
    "REWRITE_VERDICTS",
    "ReviewDestination",
    "RewriteAttempt",
    "VERDICT_AUTO_REWRITE_FAILED",
    "VERDICT_AUTO_REWRITE_SUCCEEDED",
    "VERDICT_HUMAN_APPROVAL_REQUIRED",
    "VERDICT_ORIGINAL_APPROVED",
    "SINK_TYPES",
    "SAVED_VIEW_PARAM_TYPES",
    "SQL_STATEMENT_STATES",
    "SavedAuditQuery",
    "SavedQuery",
    "SavedView",
    "SqlStatement",
    "SyncRun",
    "GENIE_FEEDBACK_VALUES",
    "GENIE_MESSAGE_ROLES",
    "GENIE_MESSAGE_STATUSES",
    "SECRET_SCOPE_PERMISSIONS",
    "SERVING_ENDPOINT_STATES",
    "SNAPSHOT_STATUSES",
    "SYNCED_TABLE_MODES",
    "SYNCED_TABLE_STATUSES",
    "AutoloaderFile",
    "GenieMessage",
    "GenieSpace",
    "GenieTrustedAsset",
    "SecretScope",
    "SecretScopeAcl",
    "SecretScopeSecret",
    "ServingEndpoint",
    "SharingProvider",
    "SyncedTable",
    "SyncedTableSnapshot",
    "SystemKey",
    "TableProfileSnapshot",
    "TableStats",
    "TagPolicyRule",
    "TaskRun",
    "UnattributedWrite",
    "Topic",
    "DataProductTopic",
    "FeedReadMarker",
    "User",
    "UserBadge",
    "UserFollow",
    "UserNotification",
    "UserProfile",
    "UserTopicFollow",
    "UserWebhookSubscription",
    "VectorIndex",
    "WORKSPACE_PIN_MODES",
    "WORKSPACE_REPO_PROVIDER_KINDS",
    "WORKSPACE_REPO_SECRET_KINDS",
    "WORKSPACE_REPO_SYNC_STATES",
    "WORKSPACE_ROLES",
    "Workspace",
    "WorkspaceCatalogPin",
    "WorkspaceMember",
    "WorkspaceRepo",
    "WorkspaceRepoSecret",
]
