"""DataProductRelease: version-bump history per DP.

One row per detected change of ``DataProduct.version`` /
``DataProduct.contract_yaml_hash``.  The YAML loader emits one
release row whenever it sees a new content hash or a version
string change.  The DP detail page renders these as a GitHub-style
release stream, and ``/releases.atom`` exposes them as RSS for
CI subscribers.
"""

from __future__ import annotations

import datetime

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column

from pointlessql.models.base import Base


class DataProductRelease(Base):
    """A single recorded release for a data product.

    Attributes:
        id: Auto-incremented primary key.
        data_product_id: FK to ``data_products.id`` (cascade delete).
        version: Version string at the time of the release (e.g.
            ``"1.0.1"``).
        contract_yaml_hash: SHA-256 of the contract yaml at release
            time — lets the UI tie a release back to the literal
            YAML state.
        released_at: Timestamp the release was detected.
        notes_md: Optional release notes (markdown).  Currently
            ``None``.2 ships the autogenerated stream;
            editorial notes are a Phase 84.2.1 follow-up.
        signed_off_by_email: Optional sign-off recorded by the
            loader when the YAML loader resolved a steward.  Empty
            string when no resolution happened.
    """

    __tablename__ = "data_product_releases"

    __table_args__ = (
        Index(
            "ix_data_product_releases_dp_released",
            "data_product_id",
            "released_at",
        ),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    data_product_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("data_products.id", ondelete="CASCADE"),
        nullable=False,
    )
    version: Mapped[str] = mapped_column(String(64), nullable=False)
    contract_yaml_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    released_at: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    notes_md: Mapped[str | None] = mapped_column(Text, nullable=True)
    signed_off_by_email: Mapped[str] = mapped_column(
        String(254), nullable=False, default="", server_default=""
    )
