"""bi dashboards

Revision ID: 0146
Revises: 0145
Create Date: 2026-06-11 10:06:50.730113
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0146"
down_revision: str | None = "0145"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bi_dashboards",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("params", sa.Text(), server_default="[]", nullable=False),
        sa.Column("public_token", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_token"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("bi_dashboards", schema=None) as batch_op:
        batch_op.create_index("ix_bi_dashboards_owner", ["owner_id"], unique=False)
        batch_op.create_index("ix_bi_dashboards_workspace", ["workspace_id"], unique=False)

    op.create_table(
        "bi_dashboard_widgets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dashboard_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("sql_text", sa.Text(), nullable=True),
        sa.Column("saved_query_id", sa.Integer(), nullable=True),
        sa.Column("markdown", sa.Text(), nullable=True),
        sa.Column("chart_spec", sa.Text(), server_default="{}", nullable=False),
        sa.Column(
            "position", sa.Text(), server_default='{"x": 0, "y": 0, "w": 6, "h": 4}', nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('chart', 'counter', 'table', 'markdown')", name="ck_bi_dashboard_widgets_kind"
        ),
        sa.ForeignKeyConstraint(["dashboard_id"], ["bi_dashboards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["saved_query_id"], ["saved_queries.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bi_dashboard_widgets", schema=None) as batch_op:
        batch_op.create_index("ix_bi_dashboard_widgets_dashboard", ["dashboard_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bi_dashboard_widgets", schema=None) as batch_op:
        batch_op.drop_index("ix_bi_dashboard_widgets_dashboard")

    op.drop_table("bi_dashboard_widgets")
    with op.batch_alter_table("bi_dashboards", schema=None) as batch_op:
        batch_op.drop_index("ix_bi_dashboards_workspace")
        batch_op.drop_index("ix_bi_dashboards_owner")

    op.drop_table("bi_dashboards")
    # ### end Alembic commands ###
