"""tag_policies

Revision ID: 0153
Revises: 0152
Create Date: 2026-06-11 18:39:58.661006
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0153"
down_revision: str | None = "0152"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag_policy_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tag_key", sa.String(length=200), nullable=False),
        sa.Column("tag_value", sa.String(length=200), nullable=True),
        sa.Column("effect", sa.String(length=20), nullable=False),
        sa.Column("expr", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="100", nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tag_policy_rules", schema=None) as batch_op:
        batch_op.create_index("ix_tag_policy_rules_active", ["is_active"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag_policy_rules", schema=None) as batch_op:
        batch_op.drop_index("ix_tag_policy_rules_active")

    op.drop_table("tag_policy_rules")
    # ### end Alembic commands ###
