"""quality_monitoring

Revision ID: 0155
Revises: 0154
Create Date: 2026-06-11 19:05:20.294053
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0155"
down_revision: str | None = "0154"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quality_monitors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("target", sa.String(length=256), nullable=False),
        sa.Column("cron_expr", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("backing_job_id", sa.Integer(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["backing_job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "target", name="uq_quality_monitors_target"),
    )
    with op.batch_alter_table("quality_monitors", schema=None) as batch_op:
        batch_op.create_index("ix_quality_monitors_workspace", ["workspace_id"], unique=False)

    op.create_table(
        "quality_anomalies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("monitor_id", sa.Integer(), nullable=False),
        sa.Column("table_fqn", sa.String(length=256), nullable=False),
        sa.Column("column_name", sa.String(length=256), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("observed", sa.String(length=400), nullable=False),
        sa.Column("expected", sa.String(length=400), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('volume_drop', 'null_spike', 'schema_change', 'freshness')",
            name="ck_quality_anomalies_kind",
        ),
        sa.CheckConstraint(
            "severity IN ('warn', 'critical')", name="ck_quality_anomalies_severity"
        ),
        sa.ForeignKeyConstraint(["monitor_id"], ["quality_monitors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quality_anomalies", schema=None) as batch_op:
        batch_op.create_index("ix_quality_anomalies_monitor", ["monitor_id"], unique=False)
        batch_op.create_index(
            "ix_quality_anomalies_open", ["monitor_id", "table_fqn", "resolved_at"], unique=False
        )

    op.create_table(
        "table_profile_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("monitor_id", sa.Integer(), nullable=False),
        sa.Column("table_fqn", sa.String(length=256), nullable=False),
        sa.Column("delta_version", sa.Integer(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("column_metrics", sa.Text(), server_default="{}", nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["monitor_id"], ["quality_monitors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("table_profile_snapshots")
    with op.batch_alter_table("quality_anomalies", schema=None) as batch_op:
        batch_op.drop_index("ix_quality_anomalies_open")
        batch_op.drop_index("ix_quality_anomalies_monitor")

    op.drop_table("quality_anomalies")
    with op.batch_alter_table("quality_monitors", schema=None) as batch_op:
        batch_op.drop_index("ix_quality_monitors_workspace")

    op.drop_table("quality_monitors")
    # ### end Alembic commands ###
