"""access_requests

Revision ID: 0157
Revises: 0156
Create Date: 2026-06-11 19:11:44.420151
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0157"
down_revision: str | None = "0156"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("securable_type", sa.String(length=32), server_default="table", nullable=False),
        sa.Column("full_name", sa.String(length=256), nullable=False),
        sa.Column("requester_user_id", sa.Integer(), nullable=False),
        sa.Column("requester_email", sa.String(length=254), nullable=False),
        sa.Column("owner_email_snapshot", sa.String(length=254), server_default="", nullable=False),
        sa.Column("privileges", sa.Text(), server_default='["SELECT"]', nullable=False),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("decided_by_user_id", sa.Integer(), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'denied', 'cancelled')",
            name="ck_access_requests_status",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("access_requests", schema=None) as batch_op:
        batch_op.create_index(
            "ix_access_requests_full_name_status", ["full_name", "status"], unique=False
        )
        batch_op.create_index(
            "ix_access_requests_workspace_status", ["workspace_id", "status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("access_requests", schema=None) as batch_op:
        batch_op.drop_index("ix_access_requests_workspace_status")
        batch_op.drop_index("ix_access_requests_full_name_status")

    op.drop_table("access_requests")
    # ### end Alembic commands ###
