"""phase209 genie online tables autoloader

Revision ID: 0e2e6c3bc25f
Revises: b2665e35c294
Create Date: 2026-06-11 13:32:38.775288
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e2e6c3bc25f"
down_revision: str | None = "b2665e35c294"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "synced_tables",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("source_fqn", sa.String(length=768), nullable=False),
        sa.Column("target_url", sa.String(length=2000), nullable=False),
        sa.Column("target_table", sa.String(length=256), nullable=False),
        sa.Column("primary_keys", sa.Text(), nullable=True),
        sa.Column("mode", sa.String(length=8), server_default="full", nullable=False),
        sa.Column("last_synced_version", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="idle", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("rows_synced", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=254), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("mode IN ('full', 'cdf')", name="ck_synced_tables_mode"),
        sa.CheckConstraint(
            "status IN ('idle', 'syncing', 'ok', 'failed')", name="ck_synced_tables_status"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "name", name="uq_synced_tables_ws_name"),
    )
    with op.batch_alter_table("synced_tables", schema=None) as batch_op:
        batch_op.create_index("ix_synced_tables_workspace", ["workspace_id"], unique=False)

    op.create_table(
        "genie_spaces",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("tables", sa.Text(), server_default="[]", nullable=False),
        sa.Column("metric_views", sa.Text(), server_default="[]", nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("genie_spaces", schema=None) as batch_op:
        batch_op.create_index("ix_genie_spaces_owner", ["owner_id"], unique=False)
        batch_op.create_index("ix_genie_spaces_workspace", ["workspace_id"], unique=False)

    op.create_table(
        "genie_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("space_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sql_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("feedback", sa.String(length=8), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('user', 'assistant')", name="ck_genie_messages_role"),
        sa.CheckConstraint("status IN ('ok', 'error')", name="ck_genie_messages_status"),
        sa.ForeignKeyConstraint(["space_id"], ["genie_spaces.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("genie_messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_genie_messages_space_created", ["space_id", "created_at"], unique=False
        )

    op.create_table(
        "genie_trusted_assets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("space_id", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(length=500), nullable=False),
        sa.Column("sql_text", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["space_id"], ["genie_spaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("genie_trusted_assets", schema=None) as batch_op:
        batch_op.create_index("ix_genie_trusted_assets_space", ["space_id"], unique=False)

    op.create_table(
        "autoloader_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ingest_source_id", sa.Integer(), nullable=False),
        sa.Column("mapping_index", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=2000), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("file_mtime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ingest_source_id"], ["ingest_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ingest_source_id",
            "mapping_index",
            "file_path",
            name="uq_autoloader_files_source_mapping_path",
        ),
    )
    with op.batch_alter_table("autoloader_files", schema=None) as batch_op:
        batch_op.create_index(
            "ix_autoloader_files_source_mapping",
            ["ingest_source_id", "mapping_index"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("autoloader_files", schema=None) as batch_op:
        batch_op.drop_index("ix_autoloader_files_source_mapping")

    op.drop_table("autoloader_files")
    with op.batch_alter_table("genie_trusted_assets", schema=None) as batch_op:
        batch_op.drop_index("ix_genie_trusted_assets_space")

    op.drop_table("genie_trusted_assets")
    with op.batch_alter_table("genie_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_genie_messages_space_created")

    op.drop_table("genie_messages")
    with op.batch_alter_table("genie_spaces", schema=None) as batch_op:
        batch_op.drop_index("ix_genie_spaces_workspace")
        batch_op.drop_index("ix_genie_spaces_owner")

    op.drop_table("genie_spaces")
    with op.batch_alter_table("synced_tables", schema=None) as batch_op:
        batch_op.drop_index("ix_synced_tables_workspace")

    op.drop_table("synced_tables")
    # ### end Alembic commands ###
