"""phase210_hosted_apps

Revision ID: 36ccd1106f39
Revises: 624dddd244f1
Create Date: 2026-06-11 19:09:13.530928
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36ccd1106f39"
down_revision: str | None = "624dddd244f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hosted_apps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source_code", sa.Text(), nullable=False),
        sa.Column("command_override", sa.Text(), nullable=True),
        sa.Column("env_json", sa.Text(), server_default="{}", nullable=False),
        sa.Column("state", sa.String(length=16), server_default="stopped", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('fastapi', 'streamlit', 'command')", name="ck_hosted_apps_kind"
        ),
        sa.CheckConstraint(
            "state IN ('stopped', 'starting', 'ready', 'failed')", name="ck_hosted_apps_state"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "slug", name="uq_hosted_apps_ws_slug"),
    )
    with op.batch_alter_table("hosted_apps", schema=None) as batch_op:
        batch_op.create_index("ix_hosted_apps_workspace", ["workspace_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hosted_apps", schema=None) as batch_op:
        batch_op.drop_index("ix_hosted_apps_workspace")

    op.drop_table("hosted_apps")
    # ### end Alembic commands ###
