"""phase210_query_profile

Revision ID: 3e87ad3932da
Revises: 0e2e6c3bc25f
Create Date: 2026-06-11 15:52:43.984034
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e87ad3932da"
down_revision: str | None = "0e2e6c3bc25f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("query_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("profile_json", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("query_history", schema=None) as batch_op:
        batch_op.drop_column("profile_json")

    # ### end Alembic commands ###
