"""phase210_bi_snapshots

Revision ID: 52a147a27a9b
Revises: 65d35b69dd11
Create Date: 2026-06-11 19:01:46.547858
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52a147a27a9b"
down_revision: str | None = "65d35b69dd11"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bi_dashboard_schedules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("dashboard_id", sa.Integer(), nullable=False),
        sa.Column("cron_expr", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("backing_job_id", sa.Integer(), nullable=True),
        sa.Column("deliver_inapp", sa.Boolean(), nullable=False),
        sa.Column("webhook_url", sa.String(length=2000), nullable=True),
        sa.Column("webhook_hmac_secret", sa.String(length=256), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["backing_job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["dashboard_id"], ["bi_dashboards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dashboard_id"),
    )
    with op.batch_alter_table("bi_dashboard_schedules", schema=None) as batch_op:
        batch_op.create_index("ix_bi_dashboard_schedules_workspace", ["workspace_id"], unique=False)

    op.create_table(
        "bi_dashboard_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("dashboard_id", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("triggered_by", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "triggered_by IN ('schedule', 'manual')", name="ck_bi_dashboard_snapshots_triggered_by"
        ),
        sa.ForeignKeyConstraint(["dashboard_id"], ["bi_dashboards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bi_dashboard_snapshots")
    with op.batch_alter_table("bi_dashboard_schedules", schema=None) as batch_op:
        batch_op.drop_index("ix_bi_dashboard_schedules_workspace")

    op.drop_table("bi_dashboard_schedules")
    # ### end Alembic commands ###
