"""phase210_jobs_v2

Revision ID: 88614bdfcc31
Revises: 3e87ad3932da
Create Date: 2026-06-11 16:34:51.275504
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88614bdfcc31"
down_revision: str | None = "3e87ad3932da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("repair_of_run_id", sa.Integer(), nullable=True))

    with op.batch_alter_table("job_tasks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("run_if", sa.String(length=30), server_default="all_success", nullable=False)
        )
        batch_op.add_column(sa.Column("for_each_json", sa.Text(), nullable=True))

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("trigger_kind", sa.String(length=20), server_default="cron", nullable=False)
        )
        batch_op.add_column(
            sa.Column("trigger_config", sa.Text(), server_default="{}", nullable=False)
        )
        batch_op.add_column(sa.Column("trigger_cursor", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("notify_on", sa.Text(), server_default="[]", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("notify_on")
        batch_op.drop_column("trigger_cursor")
        batch_op.drop_column("trigger_config")
        batch_op.drop_column("trigger_kind")

    with op.batch_alter_table("job_tasks", schema=None) as batch_op:
        batch_op.drop_column("for_each_json")
        batch_op.drop_column("run_if")

    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.drop_column("repair_of_run_id")

    # ### end Alembic commands ###
