"""phase209 secret scopes

Revision ID: a39b56247837
Revises: t8h0j2l4n6p8
Create Date: 2026-06-11 09:30:03.955755
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a39b56247837"
down_revision: str | None = "t8h0j2l4n6p8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secret_scopes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=254), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "name", name="uq_secret_scopes_ws_name"),
    )
    with op.batch_alter_table("secret_scopes", schema=None) as batch_op:
        batch_op.create_index("ix_secret_scopes_workspace", ["workspace_id"], unique=False)

    op.create_table(
        "secret_scope_acls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_id", sa.Integer(), nullable=False),
        sa.Column("principal", sa.String(length=254), nullable=False),
        sa.Column("permission", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "permission IN ('READ', 'WRITE', 'MANAGE')", name="ck_secret_scope_acls_permission"
        ),
        sa.ForeignKeyConstraint(["scope_id"], ["secret_scopes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_id", "principal", name="uq_secret_scope_acls_scope_principal"),
    )
    with op.batch_alter_table("secret_scope_acls", schema=None) as batch_op:
        batch_op.create_index("ix_secret_scope_acls_scope", ["scope_id"], unique=False)

    op.create_table(
        "secret_scope_secrets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("encrypted_value", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=254), nullable=True),
        sa.Column("updated_by", sa.String(length=254), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scope_id"], ["secret_scopes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_id", "key", name="uq_secret_scope_secrets_scope_key"),
    )
    with op.batch_alter_table("secret_scope_secrets", schema=None) as batch_op:
        batch_op.create_index("ix_secret_scope_secrets_scope", ["scope_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secret_scope_secrets", schema=None) as batch_op:
        batch_op.drop_index("ix_secret_scope_secrets_scope")

    op.drop_table("secret_scope_secrets")
    with op.batch_alter_table("secret_scope_acls", schema=None) as batch_op:
        batch_op.drop_index("ix_secret_scope_acls_scope")

    op.drop_table("secret_scope_acls")
    with op.batch_alter_table("secret_scopes", schema=None) as batch_op:
        batch_op.drop_index("ix_secret_scopes_workspace")

    op.drop_table("secret_scopes")
    # ### end Alembic commands ###
