"""phase209 pipelines

Revision ID: b2665e35c294
Revises: f34724da723a
Create Date: 2026-06-11 11:37:37.417579
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b2665e35c294'
down_revision: str | None = 'f34724da723a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('datasets', sa.Text(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.create_index('ix_pipelines_owner', ['owner_id'], unique=False)
        batch_op.create_index('ix_pipelines_workspace', ['workspace_id'], unique=False)

    op.create_table('pipeline_cursors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=256), nullable=False),
    sa.Column('source_fqn', sa.String(length=256), nullable=False),
    sa.Column('last_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'dataset_name', 'source_fqn', name='uq_pipeline_cursors_identity')
    )
    with op.batch_alter_table('pipeline_cursors', schema=None) as batch_op:
        batch_op.create_index('ix_pipeline_cursors_pipeline', ['pipeline_id'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('triggered_by', sa.String(length=254), nullable=True),
    sa.Column('metrics', sa.Text(), server_default='[]', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('running', 'ok', 'failed')", name='ck_pipeline_runs_status'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index('ix_pipeline_runs_pipeline', ['pipeline_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_pipeline_runs_pipeline')

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('pipeline_cursors', schema=None) as batch_op:
        batch_op.drop_index('ix_pipeline_cursors_pipeline')

    op.drop_table('pipeline_cursors')
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.drop_index('ix_pipelines_workspace')
        batch_op.drop_index('ix_pipelines_owner')

    op.drop_table('pipelines')
    # ### end Alembic commands ###
