"""initial schema

Revision ID: b55f1020b8a4
Revises:
Create Date: 2026-04-26 12:03:08.675112
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b55f1020b8a4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("principal", sa.String(length=255), nullable=True),
        sa.Column("agent_id", sa.String(length=255), nullable=True),
        sa.Column("notebook_path", sa.String(length=1024), nullable=False),
        sa.Column("source_snapshot_sha", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("cost_est", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("tables_touched", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("denied_reason", sa.Text(), nullable=True),
        sa.Column("runtime_versions", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.create_index("ix_agent_runs_principal", ["principal"], unique=False)
        batch_op.create_index("ix_agent_runs_started_at", ["started_at"], unique=False)
        batch_op.create_index("ix_agent_runs_status", ["status"], unique=False)

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_email", sa.String(length=254), nullable=False),
        sa.Column("actor_role", sa.String(length=20), server_default="user", nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("target", sa.String(length=500), nullable=False),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_log_created", ["created_at"], unique=False)
        batch_op.create_index("ix_audit_log_target_created", ["target", "created_at"], unique=False)
        batch_op.create_index("ix_audit_log_user_created", ["user_id", "created_at"], unique=False)

    op.create_table(
        "autoload_checkpoints",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_path", sa.String(length=2048), nullable=False),
        sa.Column("file_sha", sa.String(length=64), nullable=False),
        sa.Column("target_table", sa.String(length=512), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rows_ingested", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_table", "file_sha", name="uq_autoload_target_sha"),
    )
    with op.batch_alter_table("autoload_checkpoints", schema=None) as batch_op:
        batch_op.create_index(
            "ix_autoload_checkpoints_target_path", ["target_table", "source_path"], unique=False
        )

    op.create_table(
        "notebook_cell_run_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("kernel_session_id", sa.String(length=64), nullable=False),
        sa.Column("execution_count", sa.Integer(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="running", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notebook_cell_run_sources", schema=None) as batch_op:
        batch_op.create_index(
            "ix_notebook_cell_run_sources_path_cell",
            ["file_path", "content_hash", "started_at"],
            unique=False,
        )

    op.create_table(
        "notebook_cell_runs",
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("kernel_session_id", sa.String(length=64), nullable=False),
        sa.Column("execution_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("agent_run_id", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("file_path", "content_hash", "kernel_session_id"),
    )
    with op.batch_alter_table("notebook_cell_runs", schema=None) as batch_op:
        batch_op.create_index("ix_notebook_cell_runs_agent_run", ["agent_run_id"], unique=False)

    op.create_table(
        "notebook_outputs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("kernel_session_id", sa.String(length=64), nullable=False),
        sa.Column("output_index", sa.Integer(), nullable=False),
        sa.Column("msg_type", sa.String(length=32), nullable=False),
        sa.Column("mime_bundle", sa.Text(), nullable=False),
        sa.Column("output_metadata", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "file_path",
            "content_hash",
            "kernel_session_id",
            "output_index",
            name="uq_notebook_outputs_position",
        ),
    )
    with op.batch_alter_table("notebook_outputs", schema=None) as batch_op:
        batch_op.create_index("ix_notebook_outputs_agent_run", ["agent_run_id"], unique=False)
        batch_op.create_index(
            "ix_notebook_outputs_lookup", ["file_path", "content_hash"], unique=False
        )

    op.create_table(
        "query_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_email", sa.String(length=254), nullable=False),
        sa.Column("sql_text", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("chart_config", sa.Text(), nullable=True),
        sa.Column("agent_run_id", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("query_history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_query_history_agent_run_id",
            ["agent_run_id"],
            unique=False,
            sqlite_where=sa.text("agent_run_id IS NOT NULL"),
            postgresql_where=sa.text("agent_run_id IS NOT NULL"),
        )
        batch_op.create_index("ix_query_history_started", ["started_at"], unique=False)
        batch_op.create_index(
            "ix_query_history_user_started", ["user_id", "started_at"], unique=False
        )

    op.create_table(
        "rate_limit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bucket", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rate_limit_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_rate_limit_events_bucket_created", ["bucket", "created_at"], unique=False
        )

    op.create_table(
        "sync_run",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("catalog_name", sa.String(length=500), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("added_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("changed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("dropped_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "table_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("full_name", sa.String(length=500), nullable=False),
        sa.Column("delta_log_version", sa.BigInteger(), nullable=False),
        sa.Column("column_name", sa.String(length=255), nullable=False),
        sa.Column("stats_json", sa.Text(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "full_name", "delta_log_version", "column_name", name="uq_table_stats_col_version"
        ),
    )
    with op.batch_alter_table("table_stats", schema=None) as batch_op:
        batch_op.create_index(
            "ix_table_stats_lookup", ["full_name", "delta_log_version"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("oidc_provider", sa.String(length=500), nullable=True),
        sa.Column("oidc_subject", sa.String(length=500), nullable=True),
        sa.Column("feed_token", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("ix_users_email", ["email"], unique=True)
        batch_op.create_index(
            "ix_users_feed_token",
            ["feed_token"],
            unique=True,
            sqlite_where=sa.text("feed_token IS NOT NULL"),
            postgresql_where=sa.text("feed_token IS NOT NULL"),
        )
        batch_op.create_index(
            "ix_users_oidc_identity",
            ["oidc_provider", "oidc_subject"],
            unique=True,
            sqlite_where=sa.text("oidc_provider IS NOT NULL"),
            postgresql_where=sa.text("oidc_provider IS NOT NULL"),
        )

    op.create_table(
        "agent_run_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("fired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('pending','delivered','delivery_failed','no_destination')",
            name="ck_agent_run_events_outcome",
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    with op.batch_alter_table("agent_run_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_agent_run_events_fired", ["agent_run_id", "fired_at"], unique=False
        )

    op.create_table(
        "agent_run_operations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("op_name", sa.String(length=32), nullable=False),
        sa.Column("params_json", sa.Text(), nullable=False),
        sa.Column("target_table", sa.String(length=255), nullable=True),
        sa.Column("input_sha", sa.String(length=64), nullable=True),
        sa.Column("rows_affected", sa.Integer(), nullable=True),
        sa.Column("delta_version_before", sa.BigInteger(), nullable=True),
        sa.Column("delta_version_after", sa.BigInteger(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "op_name IN ('autoload','merge','write_table','sql')",
            name="ck_agent_run_operations_op_name",
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_run_id", "ordinal", name="uq_agent_run_operations_ordinal"),
    )
    with op.batch_alter_table("agent_run_operations", schema=None) as batch_op:
        batch_op.create_index("ix_agent_run_operations_run", ["agent_run_id"], unique=False)

    op.create_table(
        "agent_run_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("source_bytes", sa.Text(), nullable=False),
        sa.Column("source_sha", sa.String(length=64), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_run_id"),
    )
    with op.batch_alter_table("agent_run_sources", schema=None) as batch_op:
        batch_op.create_index("ix_agent_run_sources_sha", ["source_sha"], unique=False)

    op.create_table(
        "agent_run_tool_calls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column("args_json", sa.Text(), nullable=False),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("called_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_run_tool_calls", schema=None) as batch_op:
        batch_op.create_index(
            "ix_agent_run_tool_calls_run", ["agent_run_id", "called_at"], unique=False
        )

    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("secret_hash", sa.String(length=128), nullable=False),
        sa.Column("secret_prefix", sa.String(length=8), nullable=False),
        sa.Column("supervisor", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index("ix_api_keys_secret_hash", ["secret_hash"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("cron_expr", sa.String(length=120), nullable=False),
        sa.Column("run_as_user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("config", sa.Text(), server_default="{}", nullable=False),
        sa.Column("is_paused", sa.Boolean(), nullable=False),
        sa.Column("max_parallel_runs", sa.Integer(), server_default="1", nullable=False),
        sa.Column("on_failure_url", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_as_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "query_history_tables",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("query_history_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=500), nullable=False),
        sa.Column("access_type", sa.String(length=10), server_default="read", nullable=False),
        sa.ForeignKeyConstraint(
            ["query_history_id"],
            ["query_history.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("query_history_tables", schema=None) as batch_op:
        batch_op.create_index(
            "ix_query_history_tables_full_name", ["full_name", "query_history_id"], unique=False
        )

    op.create_table(
        "saved_queries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("sql_text", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("saved_queries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_saved_queries_owner_updated", ["owner_id", "updated_at"], unique=False
        )

    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("saved_query_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("cron_expr", sa.String(length=120), nullable=False),
        sa.Column("condition_op", sa.String(length=8), nullable=False),
        sa.Column("threshold", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("backing_job_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("condition_op IN ('gt','lt','eq','ne')", name="ck_alerts_condition_op"),
        sa.ForeignKeyConstraint(
            ["backing_job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["saved_query_id"],
            ["saved_queries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index("ix_alerts_owner", ["owner_id"], unique=False)

    op.create_table(
        "dashboards",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("notebook_path", sa.String(length=1000), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("kind", sa.String(length=50), server_default="python", nullable=False),
        sa.Column("config", sa.Text(), server_default="{}", nullable=False),
        sa.Column("depends_on", sa.Text(), server_default="[]", nullable=False),
        sa.Column("max_retries", sa.Integer(), server_default="0", nullable=False),
        sa.Column("retry_backoff_seconds", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alert_destinations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("webhook_url", sa.String(length=2000), nullable=True),
        sa.Column("hmac_secret", sa.String(length=256), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('webhook','feed')", name="ck_alert_destinations_kind"),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alert_destinations", schema=None) as batch_op:
        batch_op.create_index("ix_alert_destinations_alert", ["alert_id"], unique=False)
        batch_op.create_index("ix_alert_destinations_kind", ["kind"], unique=False)

    op.create_table(
        "alert_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("fired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('fired','suppressed','delivery_failed')", name="ck_alert_events_outcome"
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    with op.batch_alter_table("alert_events", schema=None) as batch_op:
        batch_op.create_index("ix_alert_events_fired", ["alert_id", "fired_at"], unique=False)

    op.create_table(
        "job_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_run_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_run_id"],
            ["job_runs.id"],
        ),
        sa.ForeignKeyConstraint(["task_id"], ["job_tasks.id"], name="fk_job_logs_task_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_run_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_run_id"],
            ["job_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["job_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task_runs", schema=None) as batch_op:
        batch_op.create_index("ix_task_runs_job_run", ["job_run_id"], unique=False)

    # ### end Alembic commands ###

    # Expression-based indexes that ``alembic --autogenerate`` skips on
    # SQLite (it cannot reflect ``CREATE INDEX … (col DESC)`` to verify
    # round-trip equality).  Listing them here keeps the model
    # ``__table_args__`` definitions as the source of truth and ensures
    # fresh migrations recreate them.
    op.execute("CREATE INDEX ix_job_runs_job_started ON job_runs (job_id, started_at DESC)")
    op.execute(
        "CREATE INDEX ix_sync_run_catalog_started ON sync_run (catalog_name, started_at DESC)"
    )


def downgrade() -> None:
    # Mirror of the upgrade-side raw-SQL block.  Drop the expression-
    # based indexes before dropping the parent tables.
    op.execute("DROP INDEX IF EXISTS ix_sync_run_catalog_started")
    op.execute("DROP INDEX IF EXISTS ix_job_runs_job_started")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_task_runs_job_run")

    op.drop_table("task_runs")
    op.drop_table("job_logs")
    with op.batch_alter_table("alert_events", schema=None) as batch_op:
        batch_op.drop_index("ix_alert_events_fired")

    op.drop_table("alert_events")
    with op.batch_alter_table("alert_destinations", schema=None) as batch_op:
        batch_op.drop_index("ix_alert_destinations_kind")
        batch_op.drop_index("ix_alert_destinations_alert")

    op.drop_table("alert_destinations")
    op.drop_table("job_tasks")
    op.drop_table("job_runs")
    op.drop_table("dashboards")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index("ix_alerts_owner")

    op.drop_table("alerts")
    with op.batch_alter_table("saved_queries", schema=None) as batch_op:
        batch_op.drop_index("ix_saved_queries_owner_updated")

    op.drop_table("saved_queries")
    with op.batch_alter_table("query_history_tables", schema=None) as batch_op:
        batch_op.drop_index("ix_query_history_tables_full_name")

    op.drop_table("query_history_tables")
    op.drop_table("jobs")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index("ix_api_keys_secret_hash")

    op.drop_table("api_keys")
    with op.batch_alter_table("agent_run_tool_calls", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_run_tool_calls_run")

    op.drop_table("agent_run_tool_calls")
    with op.batch_alter_table("agent_run_sources", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_run_sources_sha")

    op.drop_table("agent_run_sources")
    with op.batch_alter_table("agent_run_operations", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_run_operations_run")

    op.drop_table("agent_run_operations")
    with op.batch_alter_table("agent_run_events", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_run_events_fired")

    op.drop_table("agent_run_events")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_users_oidc_identity",
            sqlite_where=sa.text("oidc_provider IS NOT NULL"),
            postgresql_where=sa.text("oidc_provider IS NOT NULL"),
        )
        batch_op.drop_index(
            "ix_users_feed_token",
            sqlite_where=sa.text("feed_token IS NOT NULL"),
            postgresql_where=sa.text("feed_token IS NOT NULL"),
        )
        batch_op.drop_index("ix_users_email")

    op.drop_table("users")
    with op.batch_alter_table("table_stats", schema=None) as batch_op:
        batch_op.drop_index("ix_table_stats_lookup")

    op.drop_table("table_stats")
    op.drop_table("sync_run")
    with op.batch_alter_table("rate_limit_events", schema=None) as batch_op:
        batch_op.drop_index("ix_rate_limit_events_bucket_created")

    op.drop_table("rate_limit_events")
    with op.batch_alter_table("query_history", schema=None) as batch_op:
        batch_op.drop_index("ix_query_history_user_started")
        batch_op.drop_index("ix_query_history_started")
        batch_op.drop_index(
            "ix_query_history_agent_run_id",
            sqlite_where=sa.text("agent_run_id IS NOT NULL"),
            postgresql_where=sa.text("agent_run_id IS NOT NULL"),
        )

    op.drop_table("query_history")
    with op.batch_alter_table("notebook_outputs", schema=None) as batch_op:
        batch_op.drop_index("ix_notebook_outputs_lookup")
        batch_op.drop_index("ix_notebook_outputs_agent_run")

    op.drop_table("notebook_outputs")
    with op.batch_alter_table("notebook_cell_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_notebook_cell_runs_agent_run")

    op.drop_table("notebook_cell_runs")
    with op.batch_alter_table("notebook_cell_run_sources", schema=None) as batch_op:
        batch_op.drop_index("ix_notebook_cell_run_sources_path_cell")

    op.drop_table("notebook_cell_run_sources")
    with op.batch_alter_table("autoload_checkpoints", schema=None) as batch_op:
        batch_op.drop_index("ix_autoload_checkpoints_target_path")

    op.drop_table("autoload_checkpoints")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_log_user_created")
        batch_op.drop_index("ix_audit_log_target_created")
        batch_op.drop_index("ix_audit_log_created")

    op.drop_table("audit_log")
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_runs_status")
        batch_op.drop_index("ix_agent_runs_started_at")
        batch_op.drop_index("ix_agent_runs_principal")

    op.drop_table("agent_runs")
    # ### end Alembic commands ###
