"""phase209 sharing providers

Revision ID: f34724da723a
Revises: f416b076fe25
Create Date: 2026-06-11 10:54:10.974626
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f34724da723a"
down_revision: str | None = "f416b076fe25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sharing_providers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("endpoint_url", sa.String(length=2000), nullable=False),
        sa.Column("encrypted_token", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=254), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "name", name="uq_sharing_providers_ws_name"),
    )
    with op.batch_alter_table("sharing_providers", schema=None) as batch_op:
        batch_op.create_index("ix_sharing_providers_workspace", ["workspace_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sharing_providers", schema=None) as batch_op:
        batch_op.drop_index("ix_sharing_providers_workspace")

    op.drop_table("sharing_providers")
    # ### end Alembic commands ###
