"""phase209 serving endpoints

Revision ID: f416b076fe25
Revises: 01acfd3cf583
Create Date: 2026-06-11 10:49:45.128842
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f416b076fe25"
down_revision: str | None = "01acfd3cf583"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "serving_endpoints",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("model_name", sa.String(length=256), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), server_default="stopped", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=254), nullable=True),
        sa.Column("invocation_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_invoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('stopped', 'starting', 'ready', 'failed')", name="ck_serving_endpoints_state"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "name", name="uq_serving_endpoints_ws_name"),
    )
    with op.batch_alter_table("serving_endpoints", schema=None) as batch_op:
        batch_op.create_index("ix_serving_endpoints_workspace", ["workspace_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("serving_endpoints", schema=None) as batch_op:
        batch_op.drop_index("ix_serving_endpoints_workspace")

    op.drop_table("serving_endpoints")
    # ### end Alembic commands ###
