"""rewrite_attempts: agent SQL rewrite-attempt audit table

Phase 39 Sprint 39.2 introduces ``rewrite_attempts`` to capture each
agent SQL rewrite outcome inside an agent run.  When the Hermes
plugin's explain-first ``pql_query`` flow returns
``cost_gate_denied``, the LLM rewrites and retries; the plugin POSTs
one row here per attempt-resolution (auto-success, auto-failure,
escalation to human approval, or "agent accepted the original
verdict").  The Sprint 39.4 Grafana panel computes weekly cost
savings as ``SUM(original_cost - rewritten_cost)`` filtered to
``verdict='auto_rewrite_succeeded'``.

Revision ID: nn4p6r8t0v2y
Revises: mm3o5q7s9u1x
Create Date: 2026-05-06 22:17:01.262771
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'nn4p6r8t0v2y'
down_revision: str | None = 'mm3o5q7s9u1x'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewrite_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('original_sql_hash', sa.String(length=40), nullable=False),
    sa.Column('rewritten_sql_hash', sa.String(length=40), nullable=True),
    sa.Column('original_cost', sa.BigInteger(), nullable=False),
    sa.Column('rewritten_cost', sa.BigInteger(), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verdict IN ('auto_rewrite_succeeded','auto_rewrite_failed','human_approval_required','original_approved')", name='ck_rewrite_attempts_verdict'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'attempt_no', name='uq_rewrite_attempts_run_attempt')
    )
    with op.batch_alter_table('rewrite_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_rewrite_attempts_run', ['agent_run_id'], unique=False)
        batch_op.create_index('ix_rewrite_attempts_verdict', ['verdict'], unique=False)
        batch_op.create_index('ix_rewrite_attempts_workspace_created', ['workspace_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewrite_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_rewrite_attempts_workspace_created')
        batch_op.drop_index('ix_rewrite_attempts_verdict')
        batch_op.drop_index('ix_rewrite_attempts_run')

    op.drop_table('rewrite_attempts')
    # ### end Alembic commands ###
